<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detailed description for each parameter.
 */

return [
    'sourcePath'   => __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR,
    'languages'    => ['ru-RU'], //Add languages to the array for the language files to be generated, here are English and Russian.
    'translator'   => 'Yii::t',
    'sort'         => true,
    'removeUnused' => false,
    'markUnused'   => true,
    'only'         => ['*.php'],
    'except'       => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/messages',
        '/vendor',
    ],
    'format'       => 'php',
    'messagePath'  => __DIR__, //path of messages folder created above
    'overwrite'    => true,
];
